# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Territorio', '0004_auto_20180225_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioComunicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medio', models.CharField(max_length=254, verbose_name='Nombre del Medio')),
                ('representante_legal', models.CharField(max_length=254, verbose_name='Representante legal')),
                ('correo_electronico', models.CharField(blank=True, max_length=254, null=True, verbose_name='Correo electr\xf3nico')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tel\xe9fono')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direcci\xf3n')),
                ('estado', models.CharField(blank=True, max_length=254, null=True, verbose_name='Estado')),
                ('nombre', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='C\xe9dula')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Territorio.Ciudad', verbose_name='Ciudad')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Territorio.Localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Medio de Comunicaci\xf3n',
                'verbose_name_plural': 'Medios de Comunicaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=254, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.AddField(
            model_name='mediocomunicacion',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Periodistas.Zona', verbose_name='Zona'),
        ),
    ]
