# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='C\xf3digo')),
                ('descripcion', models.CharField(max_length=254, verbose_name='Descripci\xf3n')),
            ],
            options={
                'ordering': ['descripcion'],
                'db_table': 'Paises',
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
    ]
