# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Territorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=254, verbose_name='Descripci\xf3n')),
                ('codigo_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Territorio.Pais', verbose_name='Codigo Pais')),
            ],
            options={
                'ordering': ['codigo_pais', 'descripcion'],
                'db_table': 'Ciudades',
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
